name: Tests

on:
  push:
  workflow_dispatch:
concurrency: unity_run
defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Integration and Unit tests
    runs-on:
      group: organization/windows-gh
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            7.0.x
      #- name: Build packages
      #  env:
      #    WORKSPACE_PATH: ${{ github.workspace }}
      #  run: .\\.github\\workflows\\release\\build-packages.ps1
      - name: Run unit tests
        env: 
          PN_PUB_KEY: ${{ secrets.SDK_PUB_KEY }}
          PN_SUB_KEY: ${{ secrets.SDK_SUB_KEY }}
          PN_SEC_KEY: ${{ secrets.SDK_SEC_KEY }} 
        run: dotnet test .\\c-sharp-chat\\PubnubChatApi\\PubnubChatApi.Tests\\PubNubChatApi.Tests.csproj --verbosity normal --logger "console;verbosity=detailed"
      - name: Cancel workflow runs for commit on error
        if: failure()
        uses: ./.github/.release/actions/actions/utils/fast-jobs-failure
  all-tests:
    name: Tests
    needs: [tests]
    runs-on:
      group: organization/Default
    steps:
      - name: Tests summary
        run: echo -e "\033[38;2;95;215;0m\033[1mAll tests successfully passed"
